#!/usr/bin/env bash
# This script is displaying clock
min=1
hour=0
while [ $hour -le 12 ]; do
  echo "Hour: $hour"
  while [ $min -le 59 ]; do
	  echo "$min"
	  min=$((min + 1))
  done
  min=1
  hour=$((hour+1))
done
