#!/usr/bin/env bash

# Check if the file exists
if [ -e "$file" ]; then
    echo "school file exists"

    # Check if the file is empty
    if [ -s "$file" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "$file" ]; then
        echo "school is a regular file"
    else
        :
    fi
else
    echo "school file does not exist"
fi
